### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by nrb0** [vargaradu/Focusrite-Midi-Control#2]
Hello,

Awesome project!

I'm trying to build it but I can't really figure it out. I'm not too familiar with swift workflows.
What I did so far was to install cocoapods and run `pod install` in the repo directory, then opened your xcode project and start a build.
It fails when trying to import `SWXMLHash`, stating that the module wasn't found.

Can you provide me a bit of details into how to actually build this ?

Thanks for your help

**Comment by raduvarga** [comment]
The important thing is to open the ".xcworkspace" file, not the ".xcodeproj".

**Comment by nrb0** [comment]
So close!
Thanks that totally allowed me to build and run it

**Comment by raduvarga** [comment]
I'll add this in the doc for clarity.
If you have any other issues, let me know.

**Comment by raduvarga** [comment]
@nrb0 I've just released a completely new version that's much more stable and has more features, if you're curious you can check it out here: https://www.raduvarga.com/software/focusrite-midi-control
