### ISSUE TITLE
Focusrite server a little touchy?

### ISSUE THREAD

**Issue by xnaron** [vargaradu/Focusrite-Midi-Control#5]
Sorry I can't find a way to contact the author directly so I am creating this issue to solicit some feedback.

I have a large 3d printed volume knob and encoder connected to an esp8266 and it currently controls the master volume and the click button mutes it.  I reversed the protocol using Vargardu's code and a lot of wiresharking.  I find the focusrite server is easy to confuse it.  When I send it consecutive messages to set volume as below it will work for a bit and then freeze up and my code will need to reconnect to the client.  I ended up closing the client every tilme I make a volume adjusment which works reliably but isn't the best setup.  I also found that if I added a keep alive message every 2.5 seconds it would also confuse the focusrite server and the connection would hang or drop and I would need to reconnect.  Not sure if you can impart some wisdom here.

clientOut.print("Length=00000d <keep-alive/>");

`void setVolume(int volume) {
 if (!clientOut.connected()) {
    setupClient();
 }
 int count;
  count = 46 + String(volume).length();
   clientOut.print("Length=0000" + String(count, HEX) + " <set devid=\"1\"><item id=\"854\" value=\""+String(volume)+"\"/></set>");
   debugOff || Serial.println("Length=0000" + String(count, HEX) + " <set devid=\"1\"><item id=\"854\" value=\""+String(volume)+"\"/></set>");
 
 // debugOff || Serial.println(String(count, HEX));
  currentVol = volume;
  clientOut.stop();
}`

**Comment by raduvarga** [comment]
@xnaron I've just released a completely new version that's much more stable and has more features, if you're curious you can check it out here: https://www.raduvarga.com/software/focusrite-midi-control
