### ISSUE TITLE
Add support for TouchOSC

### ISSUE THREAD

**Issue by THorst92** [vargaradu/Focusrite-Midi-Control#9]
Hello,
this program is really great! But unfortunately i cannot control it with TouchOSC. Do you have any suggestions why?

Best regards

Thorsten Wagner

**Comment by raduvarga** [comment]
Is this a smartphone midi app? I'll take a look into it.

**Comment by THorst92** [comment]
correct, you can download it here for free: https://hexler.net/products/touchosc

**Comment by wayouthere** [comment]
Hi, great program, or so it seems.  I'm a noob, not quite sure how to set up the midi map - I want to be able to control my Focusrite 18i20 3rd Gen from a midi control surface.  I recognize this was built for an 18i8, so maybe not compatible with my device version and/or I don't know how to set up the midi map.  Is there a user guide (for noobs!)?

**Comment by raduvarga** [comment]
There is a completely new version I've just released (currently in Beta Mode) that is stable and has many more features: https://www.raduvarga.com/software/focusrite-midi-control

@THorst92 With the new version, TouchOSC is compatible.

@wayouthere The old version was pretty buggy, the new version should work and should be fairly simple to figure out.

**Comment by THorst92** [comment]
Thank you so much! It works great!
